influxdb:
  image: bagdemir/rhino-influxdb:1.0.1
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"

grafana:
  image: bagdemir/rhino-grafana:1.0.1
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
